In [16]:
import pandas as pd

nav = pd.read_csv(r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\raw\02_nav_history.csv")

nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
nav.shape

(46000, 3)

In [17]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [6]:
nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
nav.duplicated().sum()

np.int64(0)

In [18]:
nav["date"] = pd.to_datetime(nav["date"])

In [19]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [20]:
(nav["nav"] <= 0).sum()

np.int64(0)

In [21]:
nav = nav.sort_values(["amfi_code","date"])

In [22]:
nav

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [23]:
nav.to_csv(r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\processed\clean_nav.csv",index=False)

In [24]:
transactions = pd.read_csv(r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\raw\08_investor_transactions.csv")

transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [25]:
transactions.shape

(32778, 13)

In [31]:
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [32]:
transactions.duplicated().sum()

np.int64(0)

In [26]:
transactions.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [27]:
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])

In [28]:
transactions.dtypes

investor_id                   object
transaction_date      datetime64[ns]
amfi_code                      int64
transaction_type              object
amount_inr                     int64
state                         object
city                          object
city_tier                     object
age_group                     object
gender                        object
annual_income_lakh           float64
payment_mode                  object
kyc_status                    object
dtype: object

In [30]:
(transactions["amount_inr"] <= 0).sum()

np.int64(0)

In [33]:
transactions["transaction_type"].value_counts()

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [34]:
transactions["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [35]:
transactions["payment_mode"].value_counts()

payment_mode
Net Banking    8250
Cheque         8228
UPI            8154
Mandate        8146
Name: count, dtype: int64

In [36]:
transactions = transactions.sort_values(["amfi_code","transaction_date"])

In [37]:
transactions.to_csv( r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\processed\clean_transactions.csv", index=False)

In [38]:
performance = pd.read_csv(r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\raw\07_scheme_performance.csv")

In [39]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [40]:
performance.shape

(40, 19)

In [41]:
performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [42]:
performance.duplicated().sum()

np.int64(0)

In [43]:
performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [44]:
#checking anomalies

performance["risk_grade"].value_counts()

risk_grade
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

In [45]:
performance["morningstar_rating"].value_counts()

morningstar_rating
5    17
4    16
3     7
Name: count, dtype: int64

In [47]:
performance.expense_ratio_pct.describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [50]:
performance[
    (performance["expense_ratio_pct"] < 0.1) |
    (performance["expense_ratio_pct"] > 2.5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [48]:
performance["sharpe_ratio"].describe()

count    40.000000
mean      1.361750
std       1.475805
min       0.800000
25%       0.865000
50%       0.925000
75%       0.985000
max       7.680000
Name: sharpe_ratio, dtype: float64

In [51]:
performance[
    ["return_1yr_pct",
     "return_3yr_pct",
     "return_5yr_pct"]
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [52]:
performance.to_csv(r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project\data\processed\clean_performance.csv",index=False)

In [53]:
import pandas as pd
import os

base_path = r"C:\Users\WINDOWS\OneDrive\Documents\Mutual_Fund_Analytics_Project"
raw_path = base_path + r"\data\raw"
processed_path = base_path + r"\data\processed"

os.makedirs(processed_path, exist_ok=True)

In [54]:
fund_master = pd.read_csv(raw_path + r"\01_fund_master.csv")

print(fund_master.shape)
print(fund_master.isnull().sum())
print("Duplicates:", fund_master.duplicated().sum())

fund_master["launch_date"] = pd.to_datetime(fund_master["launch_date"])

print("Invalid expense ratio:", ((fund_master["expense_ratio_pct"] < 0) | (fund_master["expense_ratio_pct"] > 3)).sum())
print("Invalid SIP amount:", (fund_master["min_sip_amount"] <= 0).sum())
print("Duplicate AMFI codes:", fund_master["amfi_code"].duplicated().sum())

fund_master = fund_master.drop_duplicates()

fund_master.to_csv(processed_path + r"\clean_fund_master.csv", index=False)

(40, 15)
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64
Duplicates: 0
Invalid expense ratio: 0
Invalid SIP amount: 0
Duplicate AMFI codes: 0

In [55]:
aum = pd.read_csv(raw_path + r"\03_aum_by_fund_house.csv")

print(aum.shape)
print(aum.isnull().sum())
print("Duplicates:", aum.duplicated().sum())

aum["date"] = pd.to_datetime(aum["date"])

print("Invalid AUM:", (aum["aum_crore"] <= 0).sum())
print("Invalid scheme count:", (aum["num_schemes"] <= 0).sum())

aum = aum.drop_duplicates()

aum.to_csv(processed_path + r"\clean_aum_by_fund_house.csv", index=False)

(90, 5)
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64
Duplicates: 0
Invalid AUM: 0
Invalid scheme count: 0

In [56]:
sip = pd.read_csv(raw_path + r"\04_monthly_sip_inflows.csv")

print(sip.shape)
print(sip.isnull().sum())
print("Duplicates:", sip.duplicated().sum())

sip["month"] = pd.to_datetime(sip["month"])

print("Invalid SIP inflow:", (sip["sip_inflow_crore"] <= 0).sum())
print("Invalid active SIP accounts:", (sip["active_sip_accounts_crore"] <= 0).sum())

sip = sip.drop_duplicates()

sip.to_csv(processed_path + r"\clean_monthly_sip_inflows.csv", index=False)

(48, 6)
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64
Duplicates: 0
Invalid SIP inflow: 0
Invalid active SIP accounts: 0

In [57]:
category_inflows = pd.read_csv(raw_path + r"\05_category_inflows.csv")

print(category_inflows.shape)
print(category_inflows.isnull().sum())
print("Duplicates:", category_inflows.duplicated().sum())

category_inflows["month"] = pd.to_datetime(category_inflows["month"])

print("Invalid category inflows:", category_inflows["net_inflow_crore"].isnull().sum())

category_inflows = category_inflows.drop_duplicates()

category_inflows.to_csv(processed_path + r"\clean_category_inflows.csv", index=False)

(144, 3)
month               0
category            0
net_inflow_crore    0
dtype: int64
Duplicates: 0
Invalid category inflows: 0

In [58]:
folio = pd.read_csv(raw_path + r"\06_industry_folio_count.csv")

print(folio.shape)
print(folio.isnull().sum())
print("Duplicates:", folio.duplicated().sum())

folio["month"] = pd.to_datetime(folio["month"])

print("Invalid total folios:", (folio["total_folios_crore"] <= 0).sum())

folio = folio.drop_duplicates()

folio.to_csv(processed_path + r"\clean_industry_folio_count.csv", index=False)

(21, 6)
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64
Duplicates: 0
Invalid total folios: 0

In [59]:
holdings = pd.read_csv(raw_path + r"\09_portfolio_holdings.csv")

print(holdings.shape)
print(holdings.isnull().sum())
print("Duplicates:", holdings.duplicated().sum())

holdings["portfolio_date"] = pd.to_datetime(holdings["portfolio_date"])

print("Invalid weight %:", ((holdings["weight_pct"] < 0) | (holdings["weight_pct"] > 100)).sum())
print("Invalid market value:", (holdings["market_value_cr"] <= 0).sum())
print("Invalid stock price:", (holdings["current_price_inr"] <= 0).sum())

holdings = holdings.drop_duplicates()

holdings.to_csv(processed_path + r"\clean_portfolio_holdings.csv", index=False)

(322, 8)
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64
Duplicates: 0
Invalid weight %: 0
Invalid market value: 0
Invalid stock price: 0

In [60]:
benchmark = pd.read_csv(raw_path + r"\10_benchmark_indices.csv")

print(benchmark.shape)
print(benchmark.isnull().sum())
print("Duplicates:", benchmark.duplicated().sum())

benchmark["date"] = pd.to_datetime(benchmark["date"])

print("Invalid close value:", (benchmark["close_value"] <= 0).sum())

benchmark = benchmark.drop_duplicates()

benchmark.to_csv(processed_path + r"\clean_benchmark_indices.csv", index=False)

(8050, 3)
date           0
index_name     0
close_value    0
dtype: int64
Duplicates: 0
Invalid close value: 0